
include /opt/theos/makefiles/common.mk

THEOS_MAKE_PATH=/opt/theos/makefiles/

TWEAK_NAME = SpireInjector
SpireInjector_FILES = Injector.xmi
SpireInjector_OBJCFLAGS = -I$(THEOS_PROJECT_DIR) -F$(THEOS_PROJECT_DIR)

include $(THEOS_MAKE_PATH)/tweak.mk

