GO_EASY_ON_ME = 1
include /opt/theos/makefiles/common.mk

THEOS_MAKE_PATH=/opt/theos/makefiles/

TWEAK_NAME = SiriSwitchInjector
SiriSwitchInjector_FILES = Injector.xm
SiriSwitchInjector_OBJCFLAGS = -I$(THEOS_PROJECT_DIR) -F$(THEOS_PROJECT_DIR)

include $(THEOS_MAKE_PATH)/tweak.mk

